#!/usr/bin/env python3
"""
Quick Setup Script for JARVIS Agent

This script helps you set up all required API keys and configurations
for the JARVIS agent in one place.
"""

import os
import sys
from pathlib import Path
import getpass


def print_header():
    """Print setup header"""
    print("=" * 60)
    print("🤖 JARVIS Agent Quick Setup")
    print("=" * 60)
    print("This script will help you configure all required API keys")
    print("and settings for your JARVIS agent.")
    print()


def get_input_with_default(prompt, default="", is_secret=False):
    """Get user input with default value"""
    if default:
        prompt += f" [{default}]: "
    else:
        prompt += ": "
    
    if is_secret:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt)
    
    return value.strip() or default


def setup_env_file():
    """Setup .env file with all configurations"""
    print("🔑 OpenAI Configuration")
    print("-" * 30)
    
    openai_key = get_input_with_default(
        "Enter your OpenAI API Key", 
        os.getenv("OPENAI_API_KEY", ""),
        is_secret=True
    )
    
    model = get_input_with_default(
        "Enter OpenAI Model", 
        os.getenv("LLM_MODEL", "gpt-4o-mini")
    )
    
    temperature = get_input_with_default(
        "Enter Temperature (0.0-2.0)", 
        os.getenv("LLM_TEMPERATURE", "0.7")
    )
    
    max_tokens = get_input_with_default(
        "Enter Max Tokens", 
        os.getenv("LLM_MAX_TOKENS", "2000")
    )
    
    print("\n🏠 Google Nest Configuration (Optional)")
    print("-" * 40)
    print("Auto-discovery finds ALL thermostats automatically!")
    print("See GOOGLE_NEST_SETUP.md for detailed instructions")
    print("Press Enter to skip if not using Google Nest")
    print()
    
    nest_token = get_input_with_default(
        "Enter Google Nest Access Token", 
        os.getenv("GOOGLE_NEST_ACCESS_TOKEN", ""),
        is_secret=True
    )
    
    nest_project = get_input_with_default(
        "Enter Google Project ID", 
        os.getenv("GOOGLE_NEST_PROJECT_ID", "")
    )
    
    nest_client_id = get_input_with_default(
        "Enter Google Client ID", 
        os.getenv("GOOGLE_NEST_CLIENT_ID", ""),
        is_secret=True
    )
    
    nest_client_secret = get_input_with_default(
        "Enter Google Client Secret", 
        os.getenv("GOOGLE_NEST_CLIENT_SECRET", ""),
        is_secret=True
    )
    
    print("\n🌐 Server Configuration")
    print("-" * 25)
    
    host = get_input_with_default(
        "Enter Server Host", 
        os.getenv("SERVER_HOST", "0.0.0.0")
    )
    
    port = get_input_with_default(
        "Enter Server Port", 
        os.getenv("SERVER_PORT", "8000")
    )
    
    # Create .env file
    env_content = f"""# JARVIS Agent Configuration
# Generated by quick_setup.py
# DO NOT COMMIT TO VERSION CONTROL

# OpenAI Configuration
OPENAI_API_KEY={openai_key}
LLM_MODEL={model}
LLM_TEMPERATURE={temperature}
LLM_MAX_TOKENS={max_tokens}
LLM_TOP_P=1.0
LLM_FREQUENCY_PENALTY=0.0
LLM_PRESENCE_PENALTY=0.0
LLM_TIMEOUT=60

# Google Nest Configuration (Optional)
# Auto-discovery finds all thermostats automatically
GOOGLE_NEST_ACCESS_TOKEN={nest_token}
GOOGLE_NEST_PROJECT_ID={nest_project}
GOOGLE_NEST_CLIENT_ID={nest_client_id}
GOOGLE_NEST_CLIENT_SECRET={nest_client_secret}

# Server Configuration
SERVER_HOST={host}
SERVER_PORT={port}
DEBUG=false

# Memory Configuration
MAX_CONVERSATION_HISTORY=100
CONTEXT_WINDOW_SIZE=4000
CONVERSATION_TIMEOUT=300

# Agent Configuration
AGENT_NAME=JARVIS Assistant
ENABLE_GUARDRAILS=true
DEFAULT_PERMISSION_LEVEL=read
"""
    
    env_file = Path(__file__).parent / ".env"
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ .env file created at {env_file}")
    return True


def validate_setup():
    """Validate the setup"""
    print("\n🔍 Validating Configuration")
    print("-" * 30)
    
    # Check if .env exists
    env_file = Path(__file__).parent / ".env"
    if not env_file.exists():
        print("❌ .env file not found")
        return False
    
    # Load .env file
    with open(env_file, 'r') as f:
        env_content = f.read()
    
    # Check OpenAI API Key
    if "OPENAI_API_KEY=" in env_content and len(env_content.split("OPENAI_API_KEY=")[1].split("\n")[0]) > 10:
        print("✅ OpenAI API Key configured")
    else:
        print("❌ OpenAI API Key missing or invalid")
        return False
    
    # Check Google Nest (optional)
    if "GOOGLE_NEST_ACCESS_TOKEN=" in env_content and len(env_content.split("GOOGLE_NEST_ACCESS_TOKEN=")[1].split("\n")[0]) > 10:
        if "GOOGLE_NEST_PROJECT_ID=" in env_content and len(env_content.split("GOOGLE_NEST_PROJECT_ID=")[1].split("\n")[0]) > 0:
            print("✅ Google Nest configured with auto-discovery")
        else:
            print("⚠️  Google Nest access token found but missing project ID")
    else:
        print("⚠️  Google Nest not configured (optional)")
    
    print("✅ Configuration is valid!")
    return True


def show_next_steps():
    """Show next steps to user"""
    print("\n🚀 Next Steps")
    print("-" * 20)
    print("1. Install dependencies:")
    print("   pip install -r requirements.txt")
    print()
    print("2. Start the JARVIS agent server:")
    print("   python3 server_main.py")
    print()
    print("3. Open your web browser:")
    print("   http://localhost:8000")
    print()
    print("4. Or use the API:")
    print("   curl -X POST http://localhost:8000/chat \\")
    print("     -H 'Content-Type: application/json' \\")
    print("     -d '{\"message\": \"Hello JARVIS!\", \"session_id\": \"test\"}'")
    print()
    print("5. For Google Nest setup, see: GOOGLE_NEST_SETUP.md")
    print()
    print("🔒 Your secrets are stored in .env file (already gitignored)")


def main():
    """Main setup function"""
    print_header()
    
    try:
        # Setup environment file
        if not setup_env_file():
            print("\n❌ Setup failed.")
            return False
        
        # Validate setup
        if not validate_setup():
            print("\n❌ Setup validation failed.")
            return False
        
        # Show next steps
        show_next_steps()
        
        print("\n🎉 JARVIS Agent setup completed successfully!")
        return True
        
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
        return False
    except Exception as e:
        print(f"\n💥 Unexpected error: {str(e)}")
        return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
